import {
  DEFAULT_MODEL_PROVIDER_ID,
  defaultKunRuntimeSettings,
  defaultModelProviderSettings,
  getModelProviderPreset,
  modelProviderPresetAccountProfile,
  modelProviderPresetProfile,
  modelProviderTokenPlanProfile,
  type KunLabSettingsV1,
  type ModelProviderModelProfileV1,
  type ModelProviderProfileV1
} from '@shared/app-settings'
import type {
  AntigravitySubscriptionModelCatalog,
  ClaudeSubscriptionProbeResult,
  CursorSubscriptionModel,
  ModelProviderModelGroup,
  ModelProviderProbeResult,
  ModelsDevCatalogResult
} from '@shared/kun-gui-api'
import { createElement } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import {
  act,
  create as createRenderer,
  type ReactTestInstance,
  type ReactTestRenderer
} from 'react-test-renderer'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { useChatStore } from '../store/chat-store'
import {
  AgentsSettingsSection,
  LaboratorySettingsSection,
  modelProvidersSettingsPatch
} from './settings-section-agents'
import { FastContextSettingsPanel } from './settings-section-lab-fast-context'
import { PptAgentSettingsPanel } from './settings-section-lab-ppt'
import { ProviderModelsManager } from './settings-section-provider-models'
import {
  ProvidersSettingsSection,
  antigravityProviderCatalogPatch
} from './settings-section-providers'
import {
  enqueueSharedModelMutation,
  resetSharedProviderMutationCoordinatorForTests,
  sharedProviderMutationCoordinator
} from './shared-provider-mutation-coordinator'

const labels: Record<string, string> = {
  agentsQuickBase: 'Base',
  agentsQuickSkill: 'Skills',
  agentsQuickMcp: 'MCP',
  agentsQuickPermissions: 'Permissions',
  agentsQuickLaboratory: 'Laboratory',
  labComposerPersonaTitle: 'Personas',
  labComposerPersonaEnabled: 'Enable composer personas',
  labComposerPersonaEnabledDesc: 'Composer persona description',
  labPlanWorktreeTitle: 'Prompt-managed worktree',
  labPlanWorktreeDescription: 'Experimental Agent-managed Direct plan worktrees',
  labPlanWorktreeEnabled: 'Enable prompt-managed plan worktrees',
  labPlanWorktreeEnabledDesc: 'Disabled by default',
  labExploreTitle: 'Fast Context',
  labExploreDescription: 'Exploration tool description',
  labExploreEnabled: 'Enable fast_context',
  labExploreEnabledDesc: 'Enable description',
  labExploreModelMode: 'Model policy',
  labExploreModelModeDesc: 'Model policy description',
  labExploreModelModeInherit: 'Follow main model',
  labExploreModelModeFixed: 'Use fixed model',
  labExploreModel: 'Explore model',
  labExploreModelDesc: 'Explore model description',
  labExploreProvider: 'Explore model provider',
  labExploreReasoning: 'Explore reasoning effort',
  labExploreReasoningDesc: 'Reasoning description',
  labExploreReasoningInherit: 'Follow main reasoning',
  labExploreFast: 'Codex Fast mode',
  labExploreFastDesc: 'Fast description',
  labExploreFastUnsupportedHint: 'Fast unsupported hint',
  labPptTitle: 'PPT agent',
  labPptDescription: 'PPT tool description',
  labPptEnabled: 'Enable ppt_agent',
  labPptEnabledDesc: 'Enable description',
  labPptModelMode: 'Model policy',
  labPptModelModeDesc: 'Model policy description',
  labPptModelModeInherit: 'Follow main model',
  labPptModelModeFixed: 'Use fixed model',
  labPptModel: 'PPT model',
  labPptModelDesc: 'PPT model description',
  labPptProvider: 'PPT model provider',
  labPptReasoning: 'PPT reasoning effort',
  labPptReasoningDesc: 'Reasoning description',
  labPptReasoningInherit: 'Follow main reasoning',
  labPptFast: 'Codex Fast mode',
  labPptFastDesc: 'Fast description',
  labPptFastUnsupportedHint: 'Fast unsupported hint',
  agents: 'Agents',
  providers: 'Providers',
  providersDesc: 'Providers description',
  kunProvider: 'Provider',
  kunProviderDesc: 'Provider description',
  kunProviderSelectDesc: 'Provider select description',
  modelProviderAdd: 'Add provider',
  modelProviderAddMenuCustom: 'Custom provider…',
  modelProviderAddCustomDesc: 'Start with a blank provider and configure its endpoint and models.',
  modelProviderAddDialogTitle: 'Add a provider',
  modelProviderAddDialogDesc: 'Choose a preset or create a custom provider.',
  modelProviderAddDialogCancel: 'Close add provider dialog',
  modelProviderAddDialogSearch: 'Search provider presets…',
  modelProviderAddDialogEmpty: 'No provider presets match "{{query}}".',
  modelProviderTabConnection: 'Connection',
  modelProviderTabModels: 'Models',
  modelProviderTabCapabilities: 'Capabilities',
  modelProviderTabAdvanced: 'Advanced',
  modelProviderWorkspaceTabs: 'Provider settings tabs',
  modelProviderCompactSelect: 'Choose provider',
  modelProviderSearchPlaceholder: 'Search configured providers…',
  modelProviderSearchEmpty: 'No providers match "{{query}}".',
  modelProviderGroupPlans: 'Subscription plans',
  modelProviderSubscriptionRegions: 'Subscription plan regions',
  modelProviderSubscriptionRegionAll: 'All',
  modelProviderSubscriptionRegionChina: 'China',
  modelProviderSubscriptionRegionUnitedStates: 'United States',
  modelProviderGroupApi: 'Pay-as-you-go',
  modelProviderPlanBadge: 'Plan',
  modelProviderTokenPlanBadge: 'Token Plan',
  modelProviderPresetUpdateTag: 'Update preset',
  modelProviderAccountCount: '{{count}} accounts',
  modelProviderAddAccountHint: 'Add an independent account',
  modelProviderNewName: 'Custom provider {{index}}',
  modelProviderDraftBadge: 'Unsaved',
  modelProviderDraftSection: 'Add this provider',
  modelProviderDraftConfirm: 'Add',
  modelProviderDraftDiscard: 'Cancel',
  modelProviderDraftHintReady: 'Click Add to save this provider and switch to it.',
  modelProviderDraftHintNoKey: 'No API key yet — Add saves without activating.',
  modelProviderNeedsConfiguration: 'Needs configuration',
  modelProviderReady: 'Ready',
  modelProviderIdentitySection: 'Provider identity',
  modelProviderIdentityHint: 'Manage the provider ID under Advanced.',
  modelProviderSectionBasics: 'Provider basics',
  modelProviderSectionConnection: 'Provider connection',
  geminiCliReady: 'Antigravity CLI is ready',
  geminiSyncModels: 'Sync Antigravity models',
  geminiModelsSynced: 'Synced {{count}} Antigravity models.',
  modelProviderSectionDanger: 'Danger zone',
  modelProviderTestConnection: 'Test connection',
  modelProviderTesting: 'Testing connection…',
  modelProviderTestSuccess: 'Connected · {{latency}}ms · {{total}} models',
  modelProviderTestFailed: 'Connection failed: {{message}}',
  modelProviderSystemProxyDetected: 'System proxy {{proxy}} can reach this provider.',
  modelProviderUseDetectedProxy: 'Use detected proxy',
  modelProviderCopyError: 'Copy error',
  modelProviderErrorCopied: 'Copied',
  modelProviderPresetMissingKeyForProbe: 'Enter this provider API key first.',
  claudeSubProbeNotReady: 'Claude subscription is not ready.',
  claudeSubProbeTimeout: 'The real Claude authentication test timed out.',
  claudeSubTokenInvalid: 'Paste only the complete sk-ant-oat token.',
  modelProviderInvalidUrl: 'URL must start with http:// or https://',
  modelProviderFetchModels: 'Fetch models',
  modelProviderFetchedModels: 'Fetched {{total}} new models',
  modelProviderModelsPlaceholder: 'Type a model ID and press Enter',
  modelProviderModelCount: '{{total}} models',
  modelProviderModelRemove: 'Remove {{model}}',
  modelProviderInUse: 'In use',
  modelProviderMissingKey: 'No API key',
  modelProviderDefaultBadge: 'Default',
  modelProviderPresetBadge: 'Preset',
  modelProviderCustomBadge: 'Custom',
  modelProviderDangerHint: 'Danger hint',
  modelProviderIdLocked: 'Provider ID locked',
  modelProviderRemove: 'Remove provider',
  modelProviderName: 'Provider name',
  modelProviderId: 'Provider ID',
  modelProviderApiKey: 'Provider API key',
  modelProviderApiKeyPlaceholder: 'Enter provider API key',
  cursorSubscriptionNote: 'Enter an API key created in the Cursor dashboard.',
  cursorSubscriptionGetApiKey: 'Get Cursor API key',
  cursorSubscriptionAccount: 'Connected account: {{account}} · API key: {{keyName}}',
  cursorSubscriptionRestartRequired: 'Fully quit Kun and reopen it, then try again.',
  geminiCliApiEndpointLocked: 'Gemini CLI API endpoint is fixed.',
  geminiCliApiSubscriptionNote: 'Gemini CLI direct API keeps Kun in charge of long sessions.',
  geminiCliApiChecking: 'Checking the Gemini CLI login…',
  geminiCliApiReady: 'Gemini CLI Google login is ready',
  geminiCliApiLoginRequired: 'Gemini CLI is not signed in to Google',
  geminiCliApiMissing: 'Gemini CLI is not installed',
  geminiCliApiLoginHint: 'Run gemini and sign in with Google.',
  geminiCliApiInstallHint: 'Install and sign in to Gemini CLI.',
  geminiCliApiRecheck: 'Check login again',
  geminiCliApiSyncModels: 'Sync Gemini CLI API models',
  geminiCliApiStatusFailed: 'Could not inspect the Gemini CLI login.',
  geminiCliApiModelsSynced: 'Synced {{count}} Gemini CLI API models.',
  geminiCliApiModelsSyncFailed: 'Could not read the Gemini CLI API model catalog.',
  modelProviderBaseUrl: 'Provider base URL',
  modelProviderEndpointFormat: 'Endpoint format',
  modelProviderRetrySection: 'Failure retry',
  modelProviderRetryMaxAttempts: 'Retry attempts',
  modelProviderRetryMaxAttemptsHint: 'Applies to eligible transport failures and the HTTP statuses listed below. Excludes the initial request; default 5, maximum 10.',
  modelProviderRetryInitialDelayMs: 'Initial retry delay (ms)',
  modelProviderRetryStatusCodes: 'Retry HTTP status codes',
  modelProviderRetryStatusCodesHint: 'Separate multiple status codes with commas. Current defaults: 429,500,502,503,504.',
  modelProviderFetchEmpty: 'No models found',
  providerModelImportTitle: 'Pick models to import',
  providerModelImportSubtitle: 'Found {{total}} for {{provider}}; {{existing}} already added.',
  providerModelImportSearchPlaceholder: 'Search by model name',
  providerModelImportFilterAll: 'All types ({{count}})',
  providerModelImportSourceAll: 'All sources ({{count}})',
  providerModelImportSourceApi: 'Provider API ({{count}})',
  providerModelImportSourceCatalog: 'models.dev ({{count}})',
  providerModelImportSourceApiBadge: 'Provider API',
  providerModelImportSourceCatalogBadge: 'models.dev only',
  providerModelImportSourceBothBadge: 'API + models.dev',
  providerModelImportHideExisting: 'Hide already added ({{count}})',
  providerModelImportAlreadyAdded: 'Already added',
  providerModelImportNoneFetched: 'No models available',
  providerModelImportNoneMatch: 'No models match',
  providerModelImportSelectAllVisible: 'Select filtered ({{count}})',
  providerModelImportClearVisible: 'Clear filtered selection',
  providerModelImportSelectedCount: '{{count}} selected',
  providerModelImportCancel: 'Cancel import',
  providerModelImportConfirm: 'Import {{count}}',
  providerModelImportApplyMetadata: 'Apply model metadata',
  providerModelImportMetadataUpdates: '{{count}} existing models can be updated',
  providerModelImportProviderWarning: 'Provider verification failed: {{message}}',
  providerModelImportProviderReturnedEmpty: 'Provider API returned no models.',
  providerModelImportCatalogError: 'Catalog unavailable: {{message}}',
  providerModelImportCatalogUnmapped: 'No exact catalog mapping.',
  providerModelImportCatalogStale: 'Using cached catalog data.',
  providerModelImportContextBadge: 'Context {{value}}',
  providerModelImportOutputBadge: 'Output {{value}}',
  providerModelImportVisionBadge: 'Vision',
  providerModelImportToolsBadge: 'Tools',
  providerModelImportNoToolsBadge: 'No tools',
  providerModelImportReasoningBadge: 'Reasoning',
  modelEndpointChatCompletions: '/v1/chat/completions (openai)',
  modelEndpointResponses: '/v1/responses (openai)',
  modelEndpointMessages: '/v1/messages (anthropic)',
  modelEndpointCustomEndpoint: 'Custom full endpoint',
  modelProviderModels: 'Provider models',
  modelProviderImageCapability: 'Image capability',
  modelProviderImageCapabilityDesc: 'Image capability description',
  modelProviderImageEnable: 'Enable image',
  modelProviderImageDisable: 'Disable image',
  modelProviderSpeechCapability: 'Speech-to-text capability',
  modelProviderSpeechCapabilityDesc: 'Speech-to-text capability description',
  modelProviderTextToSpeechCapability: 'Speech generation capability',
  modelProviderTextToSpeechCapabilityDesc: 'Speech generation capability description',
  modelProviderMusicCapability: 'Music generation capability',
  modelProviderMusicCapabilityDesc: 'Music generation capability description',
  modelProviderVideoCapability: 'Video generation capability',
  modelProviderVideoCapabilityDesc: 'Video generation capability description',
  modelProviderCapabilityConfigure: 'Configure',
  modelProviderCapabilityCollapse: 'Collapse',
  modelProviderCapabilityEnabled: 'Enabled',
  modelProviderCapabilityDisabled: 'Disabled',
  modelProviderGlobalNetwork: 'Global network proxy',
  modelProviderVisionBadge: 'Vision',
  imageGenProtocol: 'Image protocol',
  imageGenProtocolOpenAi: 'OpenAI Images',
  imageGenProtocolMiniMax: 'MiniMax image_generation',
  imageGenBaseUrl: 'Image base URL',
  imageGenModel: 'Image model',
  imageGenBaseUrlPlaceholder: 'https://api.example.com/v1',
  speechToTextProtocol: 'Speech protocol',
  speechToTextBaseUrl: 'Speech API base URL',
  speechToTextModels: 'Speech models',
  textToSpeechProtocol: 'Speech generation protocol',
  textToSpeechBaseUrl: 'Speech generation base URL',
  textToSpeechBaseUrlPlaceholder: 'https://api.example.com/v1',
  textToSpeechModel: 'Speech generation model',
  musicGenerationProtocol: 'Music generation protocol',
  musicGenerationBaseUrl: 'Music generation base URL',
  musicGenerationBaseUrlPlaceholder: 'https://api.example.com/v1',
  musicGenerationModel: 'Music model',
  videoGenerationProtocol: 'Video generation protocol',
  videoGenerationBaseUrl: 'Video generation base URL',
  videoGenerationBaseUrlPlaceholder: 'https://api.example.com/v1',
  videoGenerationModel: 'Video model',
  proxyEnabled: 'Use proxy for model requests',
  proxyUrlDesc: 'Route model requests through the local HTTP proxy.',
  proxyUrlPlaceholder: 'e.g. 10808',
  proxyUrlInvalid: 'Enter a local proxy port from 1 to 65535.',
  baseUrlPlaceholder: 'https://api.example.com/v1',
  autoApplyHint: 'Changes apply automatically',
  applying: 'Applying…',
  applied: 'Applied',
  applyFailed: 'Could not apply',
  kunApiKey: 'Kun API key',
  kunApiKeyDesc: 'Kun API key description',
  kunApiKeyPlaceholder: 'Inherit API key',
  kunApiKeyInherited: 'Inherited API key',
  kunApiKeyMissing: 'Missing API key',
  kunApiKeyOverride: 'Override API key',
  kunBaseUrl: 'Kun base URL',
  kunBaseUrlDesc: 'Kun base URL description',
  kunBaseUrlPlaceholder: 'Inherit base URL',
  kunBaseUrlOfficial: 'Official base URL',
  kunBaseUrlInherited: 'Inherited base URL',
  kunBaseUrlOverride: 'Override base URL',
  kunAssistantAdvanced: 'Assistant advanced settings',
  kunAssistantAdvancedDesc: 'Assistant advanced settings description',
  autoStart: 'Auto start',
  autoStartDesc: 'Auto start description',
  port: 'Port',
  portDesc: 'Port description',
  kunBinary: 'Kun binary',
  kunBinaryDesc: 'Kun binary description',
  kunBinaryPlaceholder: 'Bundled Kun',
  kunDataDir: 'Data dir',
  kunDataDirDesc: 'Data dir description',
  kunModel: 'Model',
  kunModelDesc: 'Model description',
  kunTokenEconomy: 'Token-saving mode',
  kunTokenEconomyDesc: 'Token-saving mode description',
  kunTokenEconomySavings: 'Saved {{tokens}} tokens',
  kunTokenEconomySavingsLoading: 'Loading savings',
  kunTokenEconomySavingsEmpty: 'Savings empty',
  kunTokenEconomyAdvanced: 'Token-saving advanced settings',
  kunTokenEconomyAdvancedDesc: 'Token-saving advanced settings description',
  kunTokenEconomyOptions: 'Token-saving options',
  kunTokenEconomyOptionsDesc: 'Token-saving options description',
  kunCompressToolDescriptions: 'Compress tool descriptions',
  kunCompressToolResults: 'Compress tool results',
  kunConciseResponses: 'Concise responses',
  kunHistoryHygiene: 'History guard',
  kunHistoryHygieneDesc: 'History guard description',
  kunHistoryMaxResultLines: 'Max result lines',
  kunHistoryMaxResultBytes: 'Max result bytes',
  kunHistoryMaxResultTokens: 'Max result tokens',
  kunHistoryMaxArgumentBytes: 'Max argument bytes',
  kunHistoryMaxArgumentTokens: 'Max argument tokens',
  kunHistoryMaxArrayItems: 'Max array items',
  runtimeToken: 'Runtime token',
  runtimeTokenDesc: 'Runtime token description',
  showSecret: 'Show',
  hideSecret: 'Hide',
  kunInsecure: 'Insecure',
  kunInsecureDesc: 'Insecure description',
  kunInsecureForcedDesc: 'Insecure forced',
  kunAdvanced: 'Advanced runtime settings',
  kunAdvancedDetails: 'Storage, model context, and tool guards',
  kunAdvancedDetailsDesc: 'Per-model context policy comes from models.profiles',
  kunStorageBackend: 'Storage backend',
  kunStorageBackendDesc: 'Storage backend description',
  kunStorageHybrid: 'Hybrid storage',
  kunStorageFile: 'Pure JSONL file storage',
  kunStorageSqlitePath: 'SQLite path',
  kunStorageSqlitePathDesc: 'SQLite path description',
  kunStorageSqlitePathPlaceholder: 'Automatic SQLite path',
  kunModelContextProfile: 'Current model context policy',
  kunModelContextProfileDesc: 'Current model context policy description',
  kunModelContextModel: 'Matched model',
  kunModelContextWindow: 'Context window',
  kunModelContextSoft: 'Model soft threshold',
  kunModelContextHard: 'Model hard threshold',
  kunModelContextSourceBuiltIn: 'Built-in model config',
  kunModelContextSourceFallback: 'Fallback model config',
  kunCompactionThresholds: 'Fallback compaction thresholds',
  kunCompactionThresholdsDesc: 'Fallback compaction thresholds description',
  kunCompactionSoftThreshold: 'Fallback soft threshold',
  kunCompactionHardThreshold: 'Fallback hard threshold',
  kunCompactionSummary: 'Compaction summary',
  kunCompactionSummaryDesc: 'Compaction summary description',
  kunCompactionSummaryMode: 'Summary mode',
  kunCompactionSummaryHeuristic: 'Heuristic summary',
  kunCompactionSummaryModel: 'Model summary',
  kunCompactionSummaryTimeout: 'Summary timeout',
  kunCompactionSummaryMaxTokens: 'Summary max tokens',
  kunCompactionSummaryInputBytes: 'Summary input bytes',
  kunMaxConcurrentTurns: 'Maximum concurrent turns',
  kunMaxConcurrentTurnsDesc: 'Maximum concurrent turns description',
  kunMaxWallTime: 'Maximum turn duration',
  kunMaxWallTimeDesc: 'Maximum turn duration description',
  kunStreamIdleTimeout: 'Stream idle timeout',
  kunStreamIdleTimeoutDesc: 'Stream idle timeout description',
  kunToolStorm: 'Tool storm',
  kunToolStormDesc: 'Tool storm description',
  kunToolOutputLimits: 'Tool output limits',
  kunToolOutputLimitsDesc: 'Tool output limits description',
  kunToolOutputMaxLines: 'Tool output max lines',
  kunToolOutputMaxBytes: 'Tool output max bytes',
  kunToolArgumentRepair: 'Tool argument repair',
  kunToolArgumentRepairDesc: 'Tool argument repair description',
  kunInstructions: 'AGENTS.md instructions',
  kunInstructionsDesc: 'AGENTS.md instructions description',
  kunInstructionsDiagnostics: '1 source injected last turn',
  kunDiagnostics: 'Kun diagnostics',
  kunDiagnosticsAdvanced: 'Detailed diagnostics',
  kunDiagnosticsAdvancedDesc: 'Detailed diagnostics description',
  kunRuntimeCapabilities: 'Runtime capabilities',
  kunRuntimeCapabilitiesDesc: 'Runtime capabilities description',
  kunRuntimeModel: 'Runtime model',
  kunRuntimePid: 'Runtime PID',
  kunDiagnosticsRefresh: 'Refresh diagnostics',
  kunToolDiagnostics: 'Tool diagnostics',
  kunToolDiagnosticsDesc: 'Tool diagnostics description',
  kunDiagnosticsProviders: 'Providers',
  kunDiagnosticsMcpServers: 'MCP servers',
  kunDiagnosticsSkills: 'Discovered Skills',
  kunDiagnosticsAttachments: 'Attachments',
  kunMemoryRecords: 'Memory records',
  kunMemoryRecordsDesc: 'Memory records description',
  kunMemoryEmpty: 'No memories',
  kunMemoryDisable: 'Disable memory',
  memoryRestore: 'Restore',
  kunMemoryDelete: 'Delete memory',
  kunMemoryDisabled: 'Disabled',
  skill: 'Skill',
  skillsLocation: 'Skill location',
  skillsLocationDesc: 'Skill location description',
  skillsPath: 'Skills path',
  skillsPathDesc: 'Skills path description',
  skillsRootUnavailable: 'Unavailable',
  skillsPermissionSources: 'Skill permission sources',
  skillsPermissionSourcesDesc: 'Skill permission sources description',
  skillsPermissionEnabledRoots: 'Enabled roots',
  skillsPermissionDisabledRoots: 'Disabled roots',
  skillsPermissionWorkspaceRoots: 'Workspace roots',
  skillsPermissionGlobalRoots: 'Global roots',
  skillsPermissionDisabledIds: 'Blocked skills',
  skillsPermissionRuntimeNote: 'Only enabled skill roots reach runtime',
  skillsScanDirs: 'Scan dirs',
  skillsScanDirsDesc: 'Scan dirs description',
  skillsActions: 'Skill actions',
  skillsActionsDesc: 'Skill actions description',
  skillsOpenRoot: 'Open root',
  skillsOpenPlugins: 'Open plugins',
  mcp: 'MCP',
  mcpSearchEnabled: 'MCP search enabled',
  mcpSearchEnabledDesc: 'MCP search description',
  mcpAdvanced: 'MCP advanced settings',
  mcpAdvancedDesc: 'MCP advanced settings description',
  mcpSearchMode: 'MCP search mode',
  mcpSearchModeDesc: 'MCP search mode description',
  mcpSearchModeAuto: 'Auto mode',
  mcpSearchModeSearch: 'Search mode',
  mcpSearchModeDirect: 'Direct mode',
  mcpSearchLimits: 'MCP search limits',
  mcpSearchLimitsDesc: 'MCP search limits description',
  mcpSearchAutoThreshold: 'Auto threshold',
  mcpSearchTopKDefault: 'Default results',
  mcpSearchTopKMax: 'Max results',
  mcpSearchMinScore: 'Minimum score',
  mcpSearchDiagnostics: 'MCP search diagnostics',
  mcpSearchDiagnosticsDesc: 'MCP search diagnostics description',
  mcpSearchStatus: 'MCP search status',
  mcpSearchActive: 'Active',
  mcpSearchInactive: 'Inactive',
  mcpSearchIndexed: 'Indexed',
  mcpSearchAdvertised: 'Advertised',
  mcpPermissionSources: 'External tool permission sources',
  mcpPermissionSourcesDesc: 'External tool permission sources description',
  mcpPermissionEnabledServers: 'Enabled servers',
  mcpPermissionDisabledServers: 'Disabled servers',
  mcpPermissionUserServers: 'All-workspace scope',
  mcpPermissionWorkspaceServers: 'Workspace scope',
  mcpPermissionVisibleServers: 'Workspace-visible only',
  mcpPermissionLocalServers: 'Local commands',
  mcpPermissionRemoteServers: 'HTTP/SSE servers',
  mcpPermissionEnvServers: 'Uses env',
  mcpPermissionHeaderServers: 'Uses headers',
  mcpPermissionParseError: 'Permission preview unavailable: {{error}}',
  mcpPermissionRuntimeNote: 'Secret values stay hidden here',
  configFilePath: 'External tool config path',
  mcpPathDesc: 'MCP JSON path description',
  mcpEditor: 'MCP editor',
  mcpEditorDesc: 'Model and API credentials do not live in this MCP file',
  mcpFileStatusReady: 'MCP config ready',
  mcpFileStatusMissing: 'MCP config missing',
  loading: 'Loading',
  mcpActions: 'MCP actions',
  mcpRuntimeHint: 'MCP runtime hint',
  mcpSave: 'Save MCP config',
  mcpReload: 'Reload MCP config',
  mcpOpenDir: 'Open MCP directory',
  permissions: 'Permissions',
  toolPermissionMode: 'Tool permission mode',
  toolPermissionModeDesc: 'Tool permission mode description',
  computerUseTitle: 'Computer control',
  browserUseSettingsTitle: 'Browser',
  designQualityTitle: 'Design quality',
  graphSettingsTitle: 'Graph mode',
  toolPermissionAskForApproval: 'Ask for approval',
  toolPermissionAskForApprovalDesc: 'Approval-worthy actions ask you first',
  toolPermissionApproveForMe: 'Approve for me',
  toolPermissionApproveForMeDesc: 'Your selected model reviews approval-worthy actions',
  toolPermissionFullAccess: 'Full access',
  toolPermissionFullAccessDesc: 'Unrestricted files, host commands, and network-capable tools',
  permissionsBehaviorHint: 'Choose who reviews approval-worthy actions or grant full access',
  projectConfigTitle: 'Project MCP & Skills',
  projectConfigDescription: 'Portable project configuration',
  projectConfigSecurityHint: 'Project MCP requires digest approval',
  projectConfigWorkspaceRequired: 'Select a workspace first',
  projectConfigWorkspace: 'Project scope',
  projectConfigWorkspaceDesc: 'Fixed workspace config path',
  projectConfigStatus: 'Validation and trust',
  projectConfigStatusDesc: 'Local digest trust',
  projectConfigStatus_missing: 'File not created',
  projectConfigStatus_invalid: 'Invalid configuration',
  projectConfigStatus_valid: 'Valid configuration',
  projectConfigTrust_untrusted: 'MCP not approved',
  projectConfigTrust_trusted: 'MCP approved',
  projectConfigTrust_stale: 'Approval stale',
  projectConfigSummary: 'Project declarations',
  projectConfigSummaryDesc: 'Redacted targets',
  projectConfigMcpServers: 'Project MCP servers',
  projectConfigSkillRoots: 'Project Skill roots',
  projectConfigDisabledSkills: 'Project disabled Skills',
  projectConfigServerEnabled: 'enabled',
  projectConfigServerDisabled: 'disabled',
  projectConfigEditor: 'Project JSON',
  projectConfigEditorDesc: 'Workspace-relative paths',
  projectConfigActions: 'Project actions',
  projectConfigActionsDesc: 'Save does not approve',
  projectConfigSave: 'Save project config',
  projectConfigRefresh: 'Refresh project config',
  projectConfigOpenDir: 'Open project config dir',
  projectConfigApprove: 'Approve project MCP',
  projectConfigReapprove: 'Reapprove project MCP',
  projectConfigRevoke: 'Revoke project MCP'
}

export function t(key: string, params?: Record<string, unknown>): string {
  let value = labels[key] ?? key
  for (const [name, replacement] of Object.entries(params ?? {})) {
    value = value.split(`{{${name}}}`).join(String(replacement))
  }
  return value
}

export function baseCtx(): Record<string, unknown> {
  const noop = () => undefined
  const asyncNoop = async () => undefined
  const ref = { current: null }
  const kun = {
    ...defaultKunRuntimeSettings(),
    autoStart: true,
    runtimeToken: '',
    insecure: true
  }
  return {
    t,
    tCommon: t,
    form: { claw: { skills: { extraDirs: ['/tmp/project/.agents/skills'] } } },
    kun,
    activeApiKey: '',
    update: noop,
    updateKun: noop,
    updateSharedCredential: noop,
    sharedApiKey: '',
    sharedBaseUrl: '',
    showApiKey: false,
    setShowApiKey: noop,
    showRuntimeToken: false,
    setShowRuntimeToken: noop,
    portError: '',
    selectControlClass: 'select',
    openOnboardingPreview: noop,
    pickWorkspace: asyncNoop,
    resetWorkspaceToDefault: noop,
    workspacePickerError: '',
    guiUpdateInfo: null,
    checkingGuiUpdate: false,
    downloadingGuiUpdate: false,
    installingGuiUpdate: false,
    guiUpdateDownloaded: false,
    guiUpdateProgress: null,
    guiUpdateError: null,
    checkGuiUpdate: asyncNoop,
    downloadGuiUpdate: asyncNoop,
    installGuiUpdate: asyncNoop,
    logPath: '',
    logDirOpenError: '',
    setLogDirOpenError: noop,
    compactHomePath: (path: string) => path,
    expandHomePath: (path: string) => path,
    compactHomePathList: (values: readonly string[]) => values.join('\n'),
    expandHomePathList: (value: string) => value.split('\n').filter(Boolean),
    pickWriteWorkspace: asyncNoop,
    resetWriteWorkspaceToDefault: noop,
    writeWorkspacePickerError: '',
    writeInlineBaseUrlInherited: false,
    effectiveWriteInlineBaseUrl: '',
    writeInlineModelInherited: false,
    effectiveWriteInlineModel: '',
    setWriteDebugModalOpen: noop,
    loadWriteDebugEntries: asyncNoop,
    scrollToAgentSection: noop,
    agentsSectionRef: ref,
    skillSectionRef: ref,
    mcpSectionRef: ref,
    permissionsSectionRef: ref,
    skillRoots: [],
    skillRootsLoading: false,
    toggleSkillRoot: noop,
    skillNotice: null,
    openSkillRoot: asyncNoop,
    openPlugins: noop,
    mcpConfigPath: '/tmp/project/.kun/mcp.json',
    mcpConfigExists: true,
    mcpConfigText: '{"mcpServers":{}}',
    setMcpConfigText: noop,
    mcpLoading: false,
    mcpBusy: false,
    mcpNotice: null,
    saveMcpConfig: asyncNoop,
    loadMcpConfig: asyncNoop,
    openMcpConfigDir: asyncNoop,
    activeProjectWorkspaceRoot: '/tmp/project',
    projectConfig: {
      workspaceRoot: '/tmp/project',
      path: '/tmp/project/.kun/project.json',
      content: '{"version":1}',
      exists: true,
      status: 'valid',
      trust: 'untrusted',
      digest: 'a'.repeat(64),
      serverSummaries: [{ id: 'local', transport: 'stdio', target: 'node', enabled: true }],
      skillRootCount: 1,
      disabledSkillCount: 2
    },
    projectConfigText: '{"version":1}',
    setProjectConfigText: noop,
    projectConfigLoading: false,
    projectConfigBusy: false,
    projectConfigNotice: null,
    loadProjectConfig: asyncNoop,
    saveProjectConfig: asyncNoop,
    setProjectConfigTrust: asyncNoop,
    openProjectConfigDir: asyncNoop,
    runtimeInfo: null,
    toolDiagnostics: null,
    memoryRecords: [],
    runtimeDiagnosticsBusy: false,
    runtimeDiagnosticsNotice: null,
    refreshKunDiagnostics: asyncNoop,
    disableMemoryRecord: asyncNoop,
    deleteMemoryRecord: asyncNoop,
    pickClawWorkspace: asyncNoop,
    resetClawWorkspaceToDefault: noop,
    clawWorkspacePickerError: '',
    splitSettingsList: (value: string) => value.split('\n').filter(Boolean),
    listSettingsText: (value: string[]) => value.join('\n')
  }
}

export function instanceText(instance: ReactTestInstance): string {
  return instance.children
    .map((child) => typeof child === 'string' ? child : instanceText(child))
    .join('')
}

export function rendererText(renderer: ReactTestRenderer): string {
  return JSON.stringify(renderer.toJSON())
}

export function findButton(renderer: ReactTestRenderer, label: string): ReactTestInstance {
  const button = renderer.root.findAllByType('button')
    .find((candidate) => instanceText(candidate).trim() === label)
  expect(button, `button "${label}"`).toBeTruthy()
  return button!
}

export function findButtonContaining(renderer: ReactTestRenderer, label: string): ReactTestInstance {
  const button = renderer.root.findAllByType('button')
    .find((candidate) => instanceText(candidate).includes(label))
  expect(button, `button containing "${label}"`).toBeTruthy()
  return button!
}

export function activePanelText(renderer: ReactTestRenderer): string {
  const panels = renderer.root
    .findAllByProps({ role: 'tabpanel' })
    .filter((panel) => String(panel.props.id ?? '').startsWith('provider-settings-panel-'))
    .filter((panel) => panel.props.hidden !== true)
  expect(panels).toHaveLength(1)
  return instanceText(panels[0])
}

export async function renderProviders(ctx: Record<string, unknown>): Promise<ReactTestRenderer> {
  let renderer!: ReactTestRenderer
  await act(async () => {
    renderer = createRenderer(createElement(ProvidersSettingsSection, { ctx }))
  })
  return renderer
}

export async function clickProviderTab(renderer: ReactTestRenderer, label: string): Promise<void> {
  const tab = renderer.root.findAllByProps({ role: 'tab' })
    .find((candidate) => instanceText(candidate) === label)
  expect(tab, `tab "${label}"`).toBeTruthy()
  await act(async () => tab!.props.onClick())
}

export { AgentsSettingsSection, DEFAULT_MODEL_PROVIDER_ID, FastContextSettingsPanel, LaboratorySettingsSection, PptAgentSettingsPanel, ProviderModelsManager, ProvidersSettingsSection, act, afterEach, antigravityProviderCatalogPatch, beforeEach, createElement, createRenderer, defaultKunRuntimeSettings, defaultModelProviderSettings, describe, enqueueSharedModelMutation, expect, getModelProviderPreset, it, modelProviderPresetAccountProfile, modelProviderPresetProfile, modelProviderTokenPlanProfile, modelProvidersSettingsPatch, renderToStaticMarkup, resetSharedProviderMutationCoordinatorForTests, sharedProviderMutationCoordinator, useChatStore, vi }
export type { AntigravitySubscriptionModelCatalog, ClaudeSubscriptionProbeResult, CursorSubscriptionModel, KunLabSettingsV1, ModelProviderModelGroup, ModelProviderModelProfileV1, ModelProviderProbeResult, ModelProviderProfileV1, ModelsDevCatalogResult, ReactTestInstance, ReactTestRenderer }
