import { useShallow } from 'zustand/react/shallow'
import { useChatStore } from '../../store/chat-store'
import { normalizeWorkbenchRoute } from './workbench-route'

export function useWorkbenchChatStoreState() {
  return useChatStore(
    useShallow((s) => ({
      threads: s.threads,
      threadSearch: s.threadSearch,
      showArchivedThreads: s.showArchivedThreads,
      activeThreadId: s.activeThreadId,
      threadLoadingId: s.threadLoadingId,
      activeThreadRelation: s.activeThreadRelation,
      activeThreadParentId: s.activeThreadParentId,
      selectThread: s.selectThread,
      createThread: s.createThread,
      createConversation: s.createConversation,
      blocks: s.blocks,
      liveReasoning: s.liveReasoning,
      liveAssistant: s.liveAssistant,
      error: s.error,
      runtimeErrorDetail: s.runtimeErrorDetail,
      runtimeStatus: s.runtimeStatus,
      busy: s.busy,
      currentTurnOrchestration: s.currentTurnOrchestration,
      route: normalizeWorkbenchRoute(s.route) as typeof s.route,
      pluginHostRoute: s.pluginHostRoute,
      workspaceRoot: s.workspaceRoot,
      conversationWorkspaceRoot: s.conversationWorkspaceRoot,
      codeWorkspaceRoots: s.codeWorkspaceRoots,
      runtimeConnection: s.runtimeConnection,
      setRoute: s.setRoute,
      openCode: s.openCode,
      openWrite: s.openWrite,
      openDesign: s.openDesign,
      clearActiveThreadSelection: s.clearActiveThreadSelection,
      ensureWriteThreadForWorkspace: s.ensureWriteThreadForWorkspace,
      ensureDesignThreadForWorkspace: s.ensureDesignThreadForWorkspace,
      createWriteThread: s.createWriteThread,
      createDesignThread: s.createDesignThread,
      clearDesignHistory: s.clearDesignHistory,
      openSettings: s.openSettings,
      openPlugins: s.openPlugins,
      openClaw: s.openClaw,
      openSchedule: s.openSchedule,
      openWorkflow: s.openWorkflow,
      chooseWorkspace: s.chooseWorkspace,
      selectWorkspaceRoot: s.selectWorkspaceRoot,
      clawChannels: s.clawChannels,
      activeClawChannelId: s.activeClawChannelId,
      selectClawChannel: s.selectClawChannel,
      resetClawChannelSession: s.resetClawChannelSession,
      setClawChannelModel: s.setClawChannelModel,
      appendLocalClawTurn: s.appendLocalClawTurn,
      setError: s.setError,
      sendMessage: s.sendMessage,
      reviewActiveThread: s.reviewActiveThread,
      queuedMessages: s.queuedMessages,
      extensionComposerContexts: s.extensionComposerContexts,
      attachExtensionComposerContext: s.attachExtensionComposerContext,
      removeExtensionComposerContext: s.removeExtensionComposerContext,
      attachComposerContext: s.attachComposerContext,
      removeComposerContext: s.removeComposerContext,
      clearComposerContexts: s.clearComposerContexts,
      removeQueuedMessage: s.removeQueuedMessage,
      guideQueuedMessage: s.guideQueuedMessage,
      interrupt: s.interrupt,
      probeRuntime: s.probeRuntime,
      composerModel: s.composerModel,
      composerProviderId: s.composerProviderId,
      composerReasoningEffort: s.composerReasoningEffort,
      composerFastMode: s.composerFastMode,
      composerPickList: s.composerPickList,
      composerModelGroups: s.composerModelGroups,
      composerPersonaId: s.composerPersonaId,
      composerPersonaEnabled: s.composerPersonaEnabled,
      codeAgentPresets: s.codeAgentPresets,
      setComposerPersonaId: s.setComposerPersonaId,
      disabledSkillIds: s.disabledSkillIds,
      composerMode: s.composerMode,
      composerOrchestration: s.composerOrchestration,
      graphEnabled: s.graphEnabled,
      setComposerMode: s.setComposerMode,
      setComposerOrchestration: s.setComposerOrchestration,
      setComposerModel: s.setComposerModel,
      setComposerReasoningEffort: s.setComposerReasoningEffort,
      setComposerFastMode: s.setComposerFastMode,
      setThreadSearch: s.setThreadSearch,
      renameThread: s.renameThread,
      pinThread: s.pinThread,
      archiveThread: s.archiveThread,
      deleteThread: s.deleteThread,
      spawnSideConversation: s.spawnSideConversation,
      openSideConversationDraft: s.openSideConversationDraft,
      selectSideConversation: s.selectSideConversation,
      setSidePanelOpen: s.setSidePanelOpen,
      sideConversations: s.sideConversations,
      sidePanel: s.sidePanel
    }))
  )
}
